export const products = [
  {
    id: 1,
    title: "React js",
    description: "course that improve your skills",
    price: "2000/-month",
    img: "./images/react.png",
    quantity: 1,
  },
  {
    id: 2,
    title: "python",
    description: "course that improve your skills",
    price: "2000/-month",
    img: "./images/python.png",
    quantity: 1,
  },
  {
    id: 3,
    title: "Java course",
    description: "course that improve your skills",
    price: "2000/-month",
    img: "./images/java.png",
    quantity: 1,
  },
  {
    id: 4,
    title: "C course",
    description: "course that improve your skills",
    price: "2000/-month",
    img: "./images/C.png",
    quantity: 1,
  },
  {
    id: 5,
    title: "c++ course",
    description: "course that improve your skills",
    price: "2000/-month",
    img: "./images/c++.png",
    quantity: 1,
  },
  {
    id: 6,
    title: "Front-End-Development",
    description: "course that improve your skills",
    price: "4000/-month",
    img: "./images/fed.png",
    quantity: 1,
  },
  {
    id: 7,
    title: "Full Stack Development",
    description: "course that improve your skills",
    price: "8500/-month",
    img: "./images/fsd.png",
    quantity: 1,
  },
  {
    id: 8,
    title: "Database Management System",
    description: "course that improve your skills",
    price: "2000/-month",
    img: "./images/dbms.png",
    quantity: 1,
  },
  {
    id: 9,
    title: "Operating System",
    description: "course that improve your skills",
    price: "2000/-month",
    img: "./images/os.png",
    quantity: 1,
  },
];
